discourse_ahs_sanghaspace:
  discourse_ahs_sanghaspace_enabled:
    default: true
    client: true
  discourse_ahs_sanghaspace_topic_fields_name:
    default: "closed|accepted_answer_post_id"
    client: true
    type: list
